USE practicedb;

SELECT* FROM WORKER;
SELECT* FROM BONUS;
SELECT* FROM TITLE;

-- 1
SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

-- 2
SELECT UPPER(FIRST_NAME) FROM WORKER;

-- 3
SELECT DISTINCT(DEPARTMENT) FROM WORKER;
SELECT DISTINCT DEPARTMENT FROM WORKER ORDER BY DEPARTMENT;

-- 4
SELECT SUBSTR(FIRST_NAME, 1, 3) FROM WORKER;

-- 5
SELECT FIRST_NAME, INSTR(FIRST_NAME, "B") FROM WORKER WHERE FIRST_NAME = "AMITABH";

-- 6 
SELECT FIRST_NAME, RTRIM(FIRST_NAME) FROM WORKER;

-- 7

-- 8
SELECT  DISTINCT(DEPARTMENT), LENGTH(DEPARTMENT) FROM WORKER;

-- 9
SELECT FIRST_NAME, REPLACE(FIRST_NAME, "a", "A") FROM WORKER;

-- 10
SELECT CONCAT(FIRST_NAME, " ", LAST_NAME) AS COMPLETE_NAME FROM WORKER;

-- 11
SELECT FIRST_NAME FROM WORKER ORDER BY FIRST_NAME DESC;

-- 12
SELECT FIRST_NAME, DEPARTMENT FROM WORKER ORDER BY FIRST_NAME , DEPARTMENT DESC;

-- 13
SELECT FIRST_NAME FROM WORKER WHERE FIRST_NAME IN ('VIPUL', 'SATISH');

-- 14
SELECT FIRST_NAME FROM WORKER WHERE FIRST_NAME NOT IN ('VIPUL', 'SATISH');

-- 15
SELECT* FROM WORKER WHERE DEPARTMENT IN ('ADMIN');

-- 16
SELECT FIRST_NAME FROM WORKER WHERE FIRST_NAME LIKE '%A%';

-- 17

-- 18
SELECT* FROM WORKER WHERE FIRST_NAME LIKE '%h' AND length(FIRST_NAME) = 6;

-- 19
SELECT* FROM WORKER WHERE SALARY BETWEEN 100000 AND 500000; 

-- 20
SELECT* FROM WORKER WHERE MONTH(JOINING_DATE) = '02' AND YEAR(JOINING_DATE) = '2014'; 

-- 21
SELECT DEPARTMENT, COUNT(*) FROM WORKER WHERE DEPARTMENT = 'ADMIN';

-- 22
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME)  AS FULL_NAME FROM WORKER WHERE SALARY BETWEEN 100000 AND 500000;

-- 23
SELECT DEPARTMENT, COUNT(*) FROM WORKER GROUP BY DEPARTMENT ORDER BY COUNT(*) DESC;

-- 24 
SELECT FIRST_NAME, WORKER_ID, WORKER_TITLE FROM WORKER INNER JOIN TITLE ON WORKER_ID = WORKER_REF_ID WHERE WORKER_TITLE = 'MANAGER';

SELECT* FROM WORKER INNER JOIN TITLE ON WORKER_ID = WORKER_REF_ID;

-- 25
SELECT WORKER_TITLE, COUNT(WORKER_TITLE) FROM TITLE GROUP BY WORKER_TITLE HAVING COUNT(WORKER_TITLE)>1;

-- 26
-- SELECT* FROM WORKER WHERE IF WORKER_ID%2 ==0
SELECT* FROM WORKER WHERE MOD (WORKER_ID, 2) != 0 ;

-- 27
SELECT* FROM WORKER WHERE MOD(WORKER_ID, 2) = 0;

-- 28
CREATE TABLE WORKER_CLONE LIKE WORKER;
INSERT INTO WORKER_CLONE SELECT* FROM WORKER;
SELECT* FROM WORKER_CLONE;

-- 29 
SELECT* FROM WORKER INNER JOIN WORKER_CLONE USING(WORKER_ID);
SELECT* FROM WORKER INNER JOIN BONUS ON WORKER_ID = WORKER_REF_ID;

-- 30
SELECT WORKER.* FROM WORKER LEFT JOIN BONUS ON WORKER_ID = WORKER_REF_ID;

-- 31
-- DUAL TABLE
SELECT CURDATE(); 
SELECT NOW();

-- 32
SELECT* FROM WORKER ORDER BY SALARY DESC LIMIT 5;

-- 33
SELECT* FROM WORKER ORDER BY SALARY DESC LIMIT 4,1;

-- 34
SELECT SALARY FROM WORKER W1 
WHERE 4 = (
SELECT COUNT(DISTINCT(W2.SALARY)) 
FROM WORKER W2
WHERE W2.SALARY >= W1.SALARY
);

-- 35
SELECT* FROM WORKER W1, WORKER W2 WHERE W1.SALARY = W2.SALARY AND W1.WORKER_ID != W2.WORKER_ID;

-- 36
SELECT MAX(SALARY) FROM WORKER WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM WORKER);

-- 37
SELECT* FROM WORKER 
UNION ALL
SELECT* FROM WORKER ORDER BY WORKER_ID;

-- 38
SELECT* FROM WORKER 
WHERE WORKER_ID NOT IN(SELECT WORKER_REF_ID FROM BONUS);

-- 39
SELECT* FROM WORKER WHERE WORKER_ID <=
(SELECT COUNT(WORKER_ID)/2 FROM WORKER);

-- 40
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT)< 4;

-- 41
SELECT DEPARTMENT, COUNT(DEPARTMENT) FROM WORKER GROUP BY DEPARTMENT;

-- 42
SELECT MAX(WORKER_ID) FROM WORKER W1 WHERE (SELECT* FROM WORKER WHERE WORKER);

-- 43
SELECT* FROM WORKER WHERE WORKER_ID = (SELECT MAX(WORKER_ID) FROM WORKER);

-- 44
 (SELECT* FROM WORKER ORDER BY WORKER_ID DESC LIMIT 5) ORDER BY WORKER_ID;
 
 -- 45
SELECT W.FIRST_NAME, W.DEPARTMENT, TEMP.MAXSAL FROM (SELECT MAX(SALARY) AS MAXSAL, DEPARTMENT FROM WORKER GROUP BY DEPARTMENT) TEMP
INNER JOIN WORKER W ON TEMP.DEPARTMENT = W.DEPARTMENT AND TEMP.MAXSAL = W.SALARY;

-- 46

-- 49
SELECT SUM(SALARY), DEPARTMENT FROM WORKER GROUP BY DEPARTMENT;

-- 50
SELECT FIRST_NAME, DEPARTMENT, SALARY FROM WORKER WHERE SALARY = (SELECT MAX(SALARY) FROM WORKER);